name: 🚀 Deploy to Staging

on:
  push:
    branches: [ release/testing ]
env:
  # IDs das listas (configure em Settings → Variables)
  LIST_WAITING_DEPLOY_TESTS_ID: ${{ vars.TRELLO_LIST_WAITING_DEPLOY_TESTS_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TRELLO_API
    steps:
      - name: 🧹 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Simular deploy (substitua com seu script real)
        run: |
          echo "🚀 Iniciando deploy para staging..."
          sleep 3
          echo "✅ Deploy concluído com sucesso!"

      - name: 🔄 Mover para WAITING DEPLOY TESTS
        run: |
          # Extrai CARD_ID do último commit (ou do PR associado)
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          CARD_URL=$(echo "$LAST_COMMIT_MSG" | grep -oE 'https://trello.com/c/[a-zA-Z0-9]+')
          if [ -n "$CARD_URL" ]; then
            CARD_ID=$(echo "$CARD_URL" | awk -F'/' '{print $5}')
            echo "🚚 Movendo card $CARD_ID para WAITING DEPLOY TESTS..."
            curl -X PUT "https://api.trello.com/1/cards/${CARD_ID}" \
              --data-urlencode "idList=${{ env. LIST_WAITING_DEPLOY_TESTS_ID }" \
              --data-urlencode "key=${{ secrets.TRELLO_API_KEY }}" \
              --data-urlencode "token=${{ secrets.TRELLO_TOKEN }}"
          else
            echo "::warning::Nenhum card do Trello encontrado no commit."
          fi